-- 오답 코드

-- WITH RENTAL_FEE_CONDITION AS (
--     SELECT C.CAR_ID, C.CAR_TYPE, C.DAILY_FEE, D.DISCOUNT_RATE
--     FROM CAR_RENTAL_COMPANY_CAR C
--         LEFT OUTER JOIN (SELECT * FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN 
--                         WHERE DURATION_TYPE LIKE '30일 이상') D
--         ON C.CAR_TYPE = D.CAR_TYPE
--     WHERE C.DAILY_FEE * (1-IFNULL(D.DISCOUNT_RATE,0)/100) * 30 >= 500000
--         AND C.DAILY_FEE * (1-IFNULL(D.DISCOUNT_RATE,0)/100) * 30 < 2000000
-- ), TYPE_DATE_CONDITION AS (
--     SELECT C.CAR_ID, C.CAR_TYPE
--     FROM CAR_RENTAL_COMPANY_CAR C
--         LEFT OUTER JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY H
--         ON C.CAR_ID = H.CAR_ID
--     WHERE C.CAR_TYPE IN ('세단', 'SUV')
--         AND (H.HISTORY_ID IS NULL 
--             OR
--             (H.END_DATE < '2022-11-01' OR H.START_DATE > '2022-11-30'))
-- )

-- SELECT DISTINCT CAR_ID, CAR_TYPE, 
--     CONVERT(DAILY_FEE * (1-IFNULL(DISCOUNT_RATE/100,0)) * 30, UNSIGNED INTEGER) AS FEE
-- FROM RENTAL_FEE_CONDITION
-- WHERE (CAR_ID, CAR_TYPE) IN (SELECT * FROM TYPE_DATE_CONDITION)
-- ORDER BY 3 DESC, 2, 1 DESC;


-- 정답 코드

WITH RENTAL_FEE_CONDITION AS (
    SELECT C.CAR_ID, C.CAR_TYPE, C.DAILY_FEE, D.DISCOUNT_RATE
    FROM CAR_RENTAL_COMPANY_CAR C
        LEFT OUTER JOIN (SELECT * FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN 
                        WHERE DURATION_TYPE LIKE '30일 이상') D
        ON C.CAR_TYPE = D.CAR_TYPE
    WHERE C.DAILY_FEE * (1-IFNULL(D.DISCOUNT_RATE,0)/100) * 30 >= 500000
        AND C.DAILY_FEE * (1-IFNULL(D.DISCOUNT_RATE,0)/100) * 30 < 2000000
), TYPE_DATE_CONDITION AS (
    SELECT C.CAR_ID, C.CAR_TYPE
    FROM CAR_RENTAL_COMPANY_CAR C
    WHERE NOT EXISTS (SELECT * FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY H 
                    WHERE H.CAR_ID = C.CAR_ID 
                        AND H.START_DATE <= '2022-11-30' 
                        AND H.END_DATE >= '2022-11-01')
        AND C.CAR_TYPE IN ('세단', 'SUV')
)

SELECT DISTINCT CAR_ID, CAR_TYPE, 
    CONVERT(DAILY_FEE * (1-IFNULL(DISCOUNT_RATE/100,0)) * 30, UNSIGNED INTEGER) AS FEE
FROM RENTAL_FEE_CONDITION
WHERE (CAR_ID, CAR_TYPE) IN (SELECT * FROM TYPE_DATE_CONDITION)
ORDER BY 3 DESC, 2, 1 DESC;