-- 오답 코드

-- SELECT COUNT(*) FISH_COUNT, DATE_FORMAT(TIME, '%c') MONTH
-- FROM FISH_INFO
-- GROUP BY 2
-- HAVING COUNT(*) IS NOT NULL
-- ORDER BY 2;


-- 정답 코드

SELECT COUNT(*) FISH_COUNT, CAST(DATE_FORMAT(TIME, '%c') AS UNSIGNED) MONTH
FROM FISH_INFO
GROUP BY 2
HAVING COUNT(*) IS NOT NULL
ORDER BY 2;