WITH RECURSIVE HOURS AS (
    SELECT 0 AS HOUR
    UNION ALL
    SELECT HOUR + 1 FROM HOURS WHERE HOUR < 23
)

SELECT H.HOUR, COUNT(A.ANIMAL_ID) AS COUNT
FROM ANIMAL_OUTS A RIGHT OUTER JOIN HOURS H
    ON HOUR(A.DATETIME) = H.HOUR
GROUP BY 1
ORDER BY 1;