-- 오답 코드

-- SELECT CART_ID
-- FROM (SELECT * FROM CART_PRODUCTS WHERE NAME IN ('Milk', 'Yogurt')) MILK_YOUGURT
-- GROUP BY CART_ID
-- HAVING COUNT(*) >= 2
-- ORDER BY CART_ID;


-- 정답 코드

SELECT CART_ID
FROM (SELECT * FROM CART_PRODUCTS WHERE NAME IN ('Milk', 'Yogurt')) MILK_YOUGURT
GROUP BY CART_ID
HAVING COUNT(DISTINCT NAME) >= 2
ORDER BY CART_ID;