WITH RECURSIVE ECOLI_GENERATION AS (
    SELECT ID, 1 AS GENERATION
    FROM ECOLI_DATA
    WHERE PARENT_ID IS NULL
    
    UNION ALL
    
    -- G.ID가 부모인 모든 자식 개체 D를 찾음
    -- 자식 개체는 부모보다 한 세대 아래이므로 GENERATION + 1
    SELECT D.ID, G.GENERATION+1 AS GENERATION
    FROM ECOLI_DATA D JOIN ECOLI_GENERATION G
        ON D.PARENT_ID = G.ID
)

-- G.ID가 부모인 자식 개체 D들을 찾음
-- RIGHT JOIN => G.ID가 존재하지만, 그 ID를 부모로 갖는 D가 없다면 -> 자식이 없는 개체
-- D.ID IS NULL => 자식이 존재하지 않는 경우만 필터링
SELECT COUNT(*) COUNT, G.GENERATION
FROM ECOLI_DATA D RIGHT JOIN ECOLI_GENERATION G
    ON D.PARENT_ID = G.ID
WHERE D.ID IS NULL
GROUP BY 2
ORDER BY 2;