-- 오답 코드

-- SELECT YEAR(DIFFERENTIATION_DATE) AS YEAR, 
--     MAX(SIZE_OF_COLONY) - SIZE_OF_COLONY AS YEAR_DEV, 
--     ID
-- FROM ECOLI_DATA
-- GROUP BY YEAR
-- ORDER BY 1, 2;

-- `YEAR(DIFFERENTIATION_DATE)`로 그룹화(Group By)하고 있지만, SELECT 절에 포함된 `SIZE_OF_COLONY`, `ID`는 집계 함수(Aggregate Function)가 아님
-- 그룹 단위에서 `MAX(SIZE_OF_COLONY)`는 올바르게 집계되지만 `SIZE_OF_COLONY`는 같은 연도 그룹 내에서 어떤 한 레코드의 값일 뿐이기 때문에 실제로 계산된 `MAX - SIZE_OF_COLONY`는 정확하지 않은 값일 수 있음


-- 정답 코드

SELECT B.YEAR, (B.MAX_COLONY - A.SIZE_OF_COLONY) AS YEAR_DEV, A.ID
FROM ECOLI_DATA A 
    JOIN 
    (SELECT YEAR(DIFFERENTIATION_DATE) YEAR, MAX(SIZE_OF_COLONY) MAX_COLONY 
    FROM ECOLI_DATA 
    GROUP BY YEAR) B
    ON YEAR(A.DIFFERENTIATION_DATE) = B.YEAR
ORDER BY 1, 2;

-- 정답 코드

-- WITH MAX_SIZE_BY_YEAR AS (
--     SELECT YEAR(DIFFERENTIATION_DATE) YEAR, MAX(SIZE_OF_COLONY) MAX_COLONY
--     FROM ECOLI_DATA
--     GROUP BY YEAR
-- )
-- SELECT B.YEAR, (B.MAX_COLONY - A.SIZE_OF_COLONY) AS YEAR_DEV, A.ID
-- FROM ECOLI_DATA A JOIN MAX_SIZE_BY_YEAR B
-- 		ON YEAR(A.DIFFERENTIATION_DATE) = B.YEAR
-- ORDER BY 1, 2;