-- 오답 코드

-- SELECT MONTH(START_DATE) MONTH, CAR_ID, COUNT(*) RECORDS
-- FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
-- WHERE DATE_FORMAT(START_DATE, '%Y-%m') BETWEEN '2022-08' AND '2022-10'
-- GROUP BY MONTH(START_DATE), CAR_ID
-- HAVING COUNT(*) >= 5
-- ORDER BY 1, 2 DESC;

-- 2022년 8월부터 10월까지 월별 ID별 총 대여 횟수가 5회 이상인 것을 찾게 됨


-- 정답 코드

WITH COUNTS AS (
    SELECT CAR_ID
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
    WHERE DATE_FORMAT(START_DATE, '%Y-%m') BETWEEN '2022-08' AND '2022-10'
    GROUP BY CAR_ID
    HAVING COUNT(CAR_ID) >= 5
)
SELECT MONTH(H.START_DATE) MONTH, H.CAR_ID, COUNT(H.CAR_ID) RECORDS
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY H JOIN COUNTS C
    ON H.CAR_ID = C.CAR_ID
WHERE DATE_FORMAT(START_DATE, '%Y-%m') BETWEEN '2022-08' AND '2022-10'
GROUP BY MONTH(START_DATE), CAR_ID
ORDER BY 1, 2 DESC;