-- 오답 코드

-- SELECT CAR_ID, 
--     CASE
--         WHEN MAX(END_DATE) >= '2022-10-16' THEN '대여중'
--         ELSE '대여가능'
--     END AVAILABILITY
-- FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
-- GROUP BY CAR_ID
-- ORDER BY CAR_ID DESC;

-- `END_DATE`의 크기만으로 판단할 수 없음
-- ex) 2022-10-17 ~ 2022-10-20


-- 정답 코드

SELECT CAR_ID,
    CASE
        WHEN MAX('2022-10-16' BETWEEN START_DATE AND END_DATE) = 1 THEN '대여중'
        ELSE '대여 가능'
    END AS AVAILABILITY
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
GROUP BY CAR_ID
ORDER BY CAR_ID DESC;