-- 오답 코드

-- SELECT YEAR(SALES_DATE) YEAR, MONTH(SALES_DATE) MONTH, 
--     COUNT(DISTINCT S.USER_ID) AS PURCHASED_USERS, 
--     ROUND(COUNT(DISTINCT S.USER_ID) / COUNT(U.USER_ID), 1) AS PURCHASED_RATIO
-- FROM USER_INFO U LEFT OUTER JOIN ONLINE_SALE S
--     ON U.USER_ID = S.USER_ID
-- WHERE U.JOINED LIKE '2021%'
-- GROUP BY 1, 2
-- ORDER BY 1, 2;

-- 상품을 구매한 회원의 비율 = (해당 월에 구매한 회원 수) / (2021년에 가입한 전체 회원 수)
-- 2021년에 가입한 전체 회원 수는 월별이 아니라 고정된 수여야 함


-- 정답 코드

WITH JOINED AS (
    SELECT COUNT(*) AS COUNT_JOINED
    FROM USER_INFO
    WHERE JOINED lIKE '2021%'
)
SELECT
    YEAR(SALES_DATE) YEAR,
    MONTH(SALES_DATE) MONTH,
    COUNT(DISTINCT USER_ID) AS PURCHASED_USERS,
    ROUND((COUNT(DISTINCT USER_ID) / COUNT_JOINED), 1) AS PURCHASED_RATIO
FROM
    ONLINE_SALE, JOINED
WHERE 
    USER_ID IN (SELECT USER_ID FROM USER_INFO
                WHERE JOINED lIKE '2021%')
GROUP BY 1, 2
ORDER BY 1, 2;