-- 오답 코드

-- WITH REVIEW_COUNT AS (
--     SELECT MEMBER_ID, COUNT(REVIEW_ID) COUNT
--     FROM REST_REVIEW
--     GROUP BY MEMBER_ID
-- )

-- SELECT M.MEMBER_NAME, R.REVIEW_TEXT, DATE_FORMAT(R.REVIEW_DATE, '%Y-%m-%d') REVIEW_DATE
-- FROM MEMBER_PROFILE M JOIN REST_REVIEW R
--     ON M.MEMBER_ID = R.MEMBER_ID
-- WHERE M.MEMBER_ID IN (SELECT MEMBER_ID FROM REVIEW_COUNT HAVING MAX(COUNT))
-- ORDER BY 3, 2;


-- 정답 코드

WITH REVIEW_COUNT AS (
    SELECT MEMBER_ID, COUNT(REVIEW_ID) COUNT
    FROM REST_REVIEW
    GROUP BY MEMBER_ID
), MAX_REVIEW AS (
    SELECT MEMBER_ID
    FROM REVIEW_COUNT
    WHERE COUNT = (SELECT MAX(COUNT) FROM REVIEW_COUNT)
)

SELECT M.MEMBER_NAME, R.REVIEW_TEXT, DATE_FORMAT(R.REVIEW_DATE, '%Y-%m-%d') REVIEW_DATE
FROM MEMBER_PROFILE M JOIN REST_REVIEW R
    ON M.MEMBER_ID = R.MEMBER_ID
WHERE M.MEMBER_ID IN (SELECT * FROM MAX_REVIEW)
ORDER BY 3, 2;

-- 정답 코드

-- WITH REVIEW_CNT AS (
--     SELECT MEMBER_ID, COUNT(*) AS CNT
--     FROM REST_REVIEW
--     GROUP BY 1
--     ORDER BY 2 DESC
--     LIMIT 1
-- )
-- SELECT M.MEMBER_NAME, REVIEW_TEXT, DATE_FORMAT(REVIEW_DATE, '%Y-%m-%d') REVIEW_DATE
-- FROM MEMBER_PROFILE M JOIN REST_REVIEW R
--     ON M.MEMBER_ID = R.MEMBER_ID
-- WHERE M.MEMBER_ID = (SELECT MEMBER_ID FROM REVIEW_CNT)
-- ORDER BY 3, 2;